import { Property, PropertyValue } from './types'

export const getProperties: () => { [key: string]: Property } = () => ({
  justifyContent: ['justifyContent', 'center'],
  center: 'justifyContent-center',
  jc: 'justifyContent-center',
  between: 'justifyContent-space-between',
  alignItems: ['alignItems', 'center'],
  display: ['display', 'flex'],
  flex: 'display',
  df: 'display',
  flexDirection: ['flexDirection', 'row'],
  row: 'flexDirection-row',
  column: 'flexDirection-column',
  direction: 'flexDirection',
  flexWrap: ['flexWrap', 'wrap'], // nowrap is the default.
  wrap: 'flexWrap',
  gap: ['gap'],
  space: 'gap',
  columnGap: ['columnGap'],
  rowGap: ['rowGap'],
  borderRadius: ['borderRadius', 'medium'],
  radius: 'borderRadius',
  rounded: 'borderRadius',
  background: ['background'],
  backgroundColor: ['backgroundColor'],
  color: ['color'],
  width: ['width'],
  w: 'width',
  fullWidth: ['width', '100%'],
  height: ['height'],
  h: 'height',
  fullHeight: ['height', '100%'],
  p: ['padding'],
  pt: ['paddingTop'],
  pv: ['paddingVertical'],
  ph: ['paddingHorizontal'],
  m: ['margin'],
  mt: ['marginTop'],
  mv: ['marginVertical'],
  mh: ['marginHorizontal'],
  bg: ['background'],
  text: ['textAlign', 'center'],
  font: ['fontFamily', 'sans-serif'],
  fontWeight: ['fontWeight', 'normal', PropertyValue.string],
  bold: 'fontWeight-bold',
  weight: 'fontWeight',
  outline: ['outline', 'none'],
  border: ['border', 'none'],
  textDecoration: ['textDecoration', 'none'],
  decoration: 'textDecoration',
  boxShadow: ['box-shadow'],
  shadow: 'boxShadow',
})

export const getShortcuts = () => ({
  button: 'outline border',
  link: 'decoration',
})
