import { Property, PropertyType } from './types'

export const getProperties: () => { [key: string]: Property } = () => ({
  justifyContent: ['justifyContent', 'center'],
  center: 'justifyContent-center',
  jc: 'justifyContent-center',
  between: 'justifyContent-space-between',
  alignItems: ['alignItems', 'center'],
  items: 'alignItems',
  display: ['display', 'flex'],
  flex: 'display',
  df: 'display',
  flexDirection: ['flexDirection', 'row'],
  row: 'flexDirection-row',
  column: 'flexDirection-column',
  direction: 'flexDirection',
  flexWrap: ['flexWrap', 'wrap'], // nowrap is the default.
  wrap: 'flexWrap',
  gap: ['gap', 'medium'],
  space: 'gap',
  columnGap: ['columnGap'],
  rowGap: ['rowGap'],
  borderRadius: ['borderRadius', 'medium'],
  radius: 'borderRadius',
  rounded: 'borderRadius',
  background: ['background'],
  bg: 'background',
  backgroundColor: ['backgroundColor'],
  color: ['color'],
  width: ['width'],
  w: 'width',
  fullWidth: ['width', '100%'],
  maxWidth: ['max-width'],
  maxW: 'maxWidth',
  height: ['height'],
  h: 'height',
  fullHeight: ['height', '100%'],
  maxHeight: ['max-width'],
  maxH: 'maxWidth',
  padding: ['padding'],
  p: 'padding',
  paddingTop: ['paddingTop'],
  pt: 'paddingTop',
  paddingVertical: ['paddingVertical'],
  pv: 'paddingVertical',
  paddingHorizontal: ['paddingHorizontal'],
  ph: 'paddingHorizontal',
  margin: ['margin'],
  m: 'margin',
  marginTop: ['marginTop'],
  mt: 'marginTop',
  marginVertical: ['marginVertical'],
  mv: 'marginVertical',
  marginHorizontal: ['marginHorizontal'],
  mh: 'marginHorizontal',
  textAlign: ['textAlign', 'center'],
  text: 'textAlign',
  font: ['fontFamily', 'sans-serif'],
  fontWeight: ['fontWeight', 'normal', PropertyType.string],
  bold: 'fontWeight-bold',
  weight: 'fontWeight',
  outline: ['outline', 'none'],
  border: ['border', 'none'],
  textDecoration: ['textDecoration', 'none'],
  decoration: 'textDecoration',
  boxShadow: [
    'boxShadow',
    (size) =>
      `0 ${Math.round(size / 2)}px ${Math.round(size / 2)}px ${Math.round(size / 4)}px #000000AA`,
  ],
  shadow: 'boxShadow',
  visibility: ['visibility', 'hidden'],
  hidden: 'visibility',
  visible: 'visibility-visible',
})

export const getShortcuts = () => ({
  button: 'outline border',
  link: 'decoration',
})
